Adds -DARDUINO_ARCH_AVR to build to comply with recent library sepcs
Arduino 1.5 Library requires ARDUINO_ARCH_AVR or _SAM be defined
to support multiple architectures. The Ethernet library, for example,
cannot be compiled without one of these and instead produces the error:

  .../socket.cpp:15:47: error: no matching function for call to
  'SPIClass::beginTrans action(int, SPISettings)'
       SPI.beginTransaction(SPI_ETHERNET_SETTINGS);

We might need to determine if ARDUINO_ARCH_AVR or _SAM should be set
based on config files.